# Generated by Django 2.0.3 on 2019-08-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=11)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_dos_produtos')),
            ],
        ),
    ]
