# Generated by Django 2.0.3 on 2019-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
