# Generated by Django 2.0.3 on 2019-09-09 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojas', '0004_auto_20190906_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='implemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojas.marca')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ano',
        ),
        migrations.AddField(
            model_name='produto',
            name='descrição',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='produto',
            name='quilometragem',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='tração',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lojas.tração'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='ano_de_fabricação',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ano_de_fabricação', to='lojas.ano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='ano_do_modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ano_do_modelo', to='lojas.ano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lojas.modelo'),
            preserve_default=False,
        ),
    ]
