# Generated by Django 2.0.3 on 2019-10-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0005_auto_20190909_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_dos_produtos'),
        ),
    ]
