language: python
python: 3.6
install: pip install -r requirements.txt
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
services:
  - xvfb
before_script:
  - "export DISPLAY=99:0"
  - sleep 3
script:
  - cd socaminhoes
  - python manage.py test