language: python
python: 3.6
install: pip install -r requirements.txt
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
services:
  - xvfb
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - export DISPLAY=:99.0
  
  - sleep 3
script:
  - cd socaminhoes
  - python manage.py test