# Generated by Django 2.0.3 on 2019-10-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='celular',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(default='guaramirim', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
